sonar.projectKey=Varelaso32_reservas-laboratorios-backend
sonar.organization=varelaso32
sonar.projectName=reservas-laboratorios-backend
sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/__pycache__/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
